---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes
    
- name: "upgrade packages."
  become: true
  apt:
    upgrade: yes

- name: "remove dependencies that are no longer required."
  become: true
  apt:
    autoremove: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
    
- name: Ensure pip is installed
  package:
    name: python{{ '3' if ansible_python.version.major == 3 else '' }}-pip
    state: present
    update_cache: true

- name: Ensure awscli python package is installed
  pip:
    name: awscli
    state: "{{ awscli_package_state }}"

- name: Ensure ~/.aws directory exists
  file:
    group: "{{ item.group }}"
    mode: 0755
    owner: "{{ item.name }}"
    path: "{{ item.home }}/.aws"
    state: directory
  loop: "{{ awscli_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Ensure ~/.aws/config file exists
  template:
    dest: "{{ item.home }}/.aws/config"
    group: "{{ item.group }}"
    mode: 0644
    owner: "{{ item.name }}"
    src: config.j2
  loop: "{{ awscli_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Ensure ~/.aws/credentials file exists
  template:
    dest: "{{ item.home }}/.aws/credentials"
    group: "{{ item.group }}"
    mode: 0644
    owner: "{{ item.name }}"
    src: credentials.j2
  loop: "{{ awscli_users }}"
  loop_control:
    label: "{{ item.name }}"
    
#- name: create directory
#file:
#  path: ~/web
#  state: directory
  
#- name: copy index test page
#  template:
#    src: "files/index.js"
#    dest: "~/web/index.js"
    
#- name: Excuting node
#  shell: |
#    pm2 start ~/web/index.js -f
