---
- name: Ensure pip is installed
  package:
    name: python{{ '3' if ansible_python.version.major == 3 else '' }}-pip
    state: present
    update_cache: true

- name: Ensure awscli python package is installed
  pip:
    name: awscli
    state: "{{ awscli_package_state }}"

- name: Ensure ~/.aws directory exists
  file:
    group: "{{ item.group }}"
    mode: 0755
    owner: "{{ item.name }}"
    path: "{{ item.home }}/.aws"
    state: directory
  loop: "{{ awscli_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Ensure ~/.aws/config file exists
  template:
    dest: "{{ item.home }}/.aws/config"
    group: "{{ item.group }}"
    mode: 0644
    owner: "{{ item.name }}"
    src: config.j2
  loop: "{{ awscli_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Ensure ~/.aws/credentials file exists
  template:
    dest: "{{ item.home }}/.aws/credentials"
    group: "{{ item.group }}"
    mode: 0644
    owner: "{{ item.name }}"
    src: credentials.j2
  loop: "{{ awscli_users }}"
  loop_control:
    label: "{{ item.name }}"
    
#-------------------------------------------------------------------------------------------------------------------------------------
- name: "install prometheus."
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "move binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/prometheus-0.17.0.linux-amd64/prometheus
    dest: /usr/local/bin/prometheus
    remote_src: yes
    mode: '0777'
    
- name: "add1 prometheus.yml"
  become: true
  copy:
    src: prometheus.yml
    dest: /prometheus-2.19.0.linux-amd64/
- name: "add2 prometheus.yml"
  become: true
  copy:
    src: prometheus.yml
    dest: /etc/prometheus/
    
- name: "add1 rules.yml"
  become: true
  copy:
    src: rules.yml
    dest: /prometheus-2.19.0.linux-amd64/
- name: "add2 rules.yml"
  become: true
  copy:
    src: rules.yml
    dest: /etc/prometheus/
    
- name: "add prometheus configuration service"
  become: true
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/
#------------------------------------------------------------------------------------------------------
- name: "install Alertmanager."
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes
    
- name: "move binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/alertmanager-0.21.0.linux-amd64/alertmanager
    dest: /usr/local/bin/alertmanager
    remote_src: yes
    mode: '0777'
    
- name: "add1 alertmanager.yml"
  become: true
  copy:
    src: alertmanager.yml
    dest: /prometheus-2.19.0.linux-amd64/
- name: "add2 alertmanager.yml"
  become: true
  copy:
    src: alertmanager.yml
    dest: /etc/prometheus/
#------------------------------------------------------------------------------------------------------
- name: "enable alertmanager service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: alertmanager
    enabled: yes
    
- name: "enable prometheus service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: prometheus
    enabled: yes
