global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'
  # slack webhook url

route:
  receiver: 'slack-notifications'
  # All alerts in a notification have the same value for these labels.
  #group_by: [alertname, datacenter, app]
receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#monitoring_instances'
    send_resolved: true
